### ISSUE TITLE
[SPARK- 2.4.7] Spark connector for Azure sql for Spark 2.4 and Scala 2.12

### ISSUE THREAD

**Issue by tejaswichandra** [microsoft/sql-spark-connector#146]
Hello,

I'm getting errors while reading from Azure SQL using Spark.

Version active in the cluster:
Spark version: 2.4.7
Scala: 2.12.10

I didn't find any suitable connector version with Spark 2.4 and Scala 2.12.

getting below error with com.microsoft.azure:spark-mssql-connector:1.0.2 :

`java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
  at com.microsoft.sqlserver.jdbc.spark.DefaultSource.<init>(DefaultSource.scala:32)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at java.lang.Class.newInstance(Class.java:442)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:327)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:242)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:230)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:186)
  ... 49 elided
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging$class
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  ... 59 more
`

Getting below error  with com.microsoft.azure:spark-mssql-connector_2.12:1.1.0 :
`java.sql.SQLException: No suitable driver
  at java.sql.DriverManager.getDriver(DriverManager.java:315)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$2(JDBCOptions.scala:105)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:105)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:35)
  at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:32)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:332)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:242)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:230)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:186)
  ... 57 elided
`

Code:
`  val jdbc_df = spark.read
                .format("com.microsoft.sqlserver.jdbc.spark")
                .option("url", url)
                .option("dbtable", dbtable)
                .option("authentication", "ActiveDirectoryPassword")
                .option("user", user)
                .option("password", password)
                .option("encrypt", "true")
                .option("hostNameInCertificate", "*.database.windows.net")
                .load()`

**Comment by luxu1-ms** [comment]
The released spark 2.4 connector only supports scala 2.11, and the spark 3.0 / 3.1 connector only support scala 2.12.
