### ISSUE TITLE
try to use partitionColumn to parallel loading using timestamp column causing exception

### ISSUE THREAD

**Issue by ruiyang2015** [microsoft/sql-spark-connector#152]
Get following exception:
>org.apache.spark.SparkException: Job aborted due to stage failure: Task 7 in stage 0.0 failed 4 times, most recent failure: Lost task 7.3 in stage 0.0 (TID 18, 10.0.118.9, executor 1): com.microsoft.sqlserver.jdbc.SQLServerException: The conversion of a varchar data type to a smalldatetime data type resulted in an out-of-range value.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5471)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1794)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1052)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anon$1.getNext(JdbcUtils.scala:358)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anon$1.getNext(JdbcUtils.scala:344)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)

when trying to load like this:
> spark.read.format("com.microsoft.sqlserver.jdbc.spark").option('partitionColumn', 'mydatetime').option('lowerBound', '2021-10-01 00:00:00').option('upperBound', '2099-12-31 23:59:59').load(...)

what is the right way to set the date time value as partition load?

**Comment by luxu1-ms** [comment]
@ruiyang2015 I think there are issues with your uppder bound '2099-12-31 23:59:59'. From error mssage, the conversion of varchar to smalldatatime resulted in an out-of-range value. The max year of smalldatetime is 2079. Please refer to this https://docs.microsoft.com/en-us/sql/t-sql/data-types/smalldatetime-transact-sql?view=sql-server-ver15.

**Comment by ruiyang2015** [comment]
why spark timestamp column is converted to a smalldatetime column? anyway to force it to be a bigger date time value?

**Comment by luxu1-ms** [comment]
I guess the datatype smalldatetime is the same as your partition column datatype.

**Comment by luxu1-ms** [comment]
Inactive issue
