### ISSUE TITLE
java.lang.NoClassDefFoundError: com/microsoft/sqlserver/jdbc/ISQLServerBulkData

### ISSUE THREAD

**Issue by learndataisfun** [microsoft/sql-spark-connector#166]
HI, I'm trying to following the examples here: https://github.com/microsoft/sql-spark-connector, with the following code:

spark = SparkSession.builder.master("local[*]")\
.config("spark.jars.packages","com.microsoft.azure:spark-mssql-connector_2.12:1.2.0,com.microsoft.sqlserver:mssql-jdbc:8.4.1.jre8")\
.config("spark.jars","\\spark-mssql-connector_2.12-1.2.0.jar,\\sqljdbc_8.4\\enu\\mssql-jdbc-8.4.1.jre8.jar")\
.config("spark.driver.extraClassPath","\\spark-mssql-connector_2.12-1.2.0.jar,\\sqljdbc_8.4\\enu\\mssql-jdbc-8.4.1.jre8.jar")\
.config("spark.executor.extraClassPath","\\spark-mssql-connector_2.12-1.2.0.jar,\\sqljdbc_8.4\\enu\\mssql-jdbc-8.4.1.jre8.jar")\
.getOrCreate()

server_name = "jdbc:sqlserver://pysparktest.database.windows.net"
database_name = "database_name"
url = server_name + ";" + "databaseName=" + database_name + ";"

table_name = "table_name"
username = "username"
password = "password123!#"

df = spark.read.format("com.microsoft.sqlserver.jdbc.spark") \
        .option("url", url) \
        .option("user",user)\
        .option("password",passw)\
        .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")\
        .option('dbtable',"SalesLT.Customer")\
        .load()

####Reading from the SQL server is no problem after struggling a lot.

try:
    df1.write \
    .format("com.microsoft.sqlserver.jdbc.spark") \
    .mode("append") \
    .option("url", url) \
    .option("dbtable", "test") \
    .option("user", user) \
    .option("password", passw) \
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")\
    .option("bulkCopyBatchSize","400") \
    .option("bulkCopyTableLock","true") \
    .option("bulkCopyTimeout","600") \
    .save()
except ValueError as error :
    print("Connector write failed", error)

####When I tried to write to a new table or append to the existing table, it gives the following exception, tried search online for a long time, no success, your help is greatly appreciated!

Py4JJavaError: An error occurred while calling o116.save.
: java.lang.NoClassDefFoundError: com/microsoft/sqlserver/jdbc/ISQLServerBulkData
	at com.microsoft.sqlserver.jdbc.spark.DefaultSource.createRelation(DefaultSource.scala:57)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

##############################
Windows 11
java 8
python = 3.8
pyspark = 3.1.2
Spark version = 3.1.2 standalone

**Comment by luxu1-ms** [comment]
Could you check your jdbc version? I guess the spark mssql connector you use is compatible with jdbc 8.4.1, but the jdbc in your environment is jdbc-7.*

**Comment by luxu1-ms** [comment]
Close inactive incident
