### ISSUE TITLE
Update documentation to mention mssql-jdbc jar as dependency

### ISSUE THREAD

**Issue by pprasad009** [microsoft/sql-spark-connector#176]
I think it would be good to explicitly callout the dependency on the `mssql-jdbc-<compatible_version>.<jre_version>.jar` driver in documentation somewhere

I was getting `java.sql.SQLException: No suitable driver` while trying to connect to database server using this driver.

It worked fine when I installed the library on databricks cluster but when I built a local docker image with spark 3.1.2 I received `No suitable driver found error`

When I passed `.option("driver","com.microsoft.sqlserver.jdbc.spark")` I received `java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.spark` error

After multiple trial and error I was able to resolve this by uploading mssql jdbc driver corresponding to my java runtime version to spark jars and/or to your classpath

steps to download the jar are mentioned in https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server

Thanks!

**Comment by luxu1-ms** [comment]
@pprasad009 We have compatible jdbc version support mentioned in README.md. Hope this could help. If we see more similar issues, we will add this to commonly faced issues.

**Comment by RicardoAcostaG** [comment]
Hello prasad009, to read I think you have overcome the impediment you had.
I have the same scenario as yours, but I couldn't get over it.

I am using: `spark-3.1.3-bin-hadoop3.2`, with `java 1.8.0_321`
`.set("spark.driver.extraClassPath","C:/mssql/mssql-jdbc-8.4.1.jre8.jar")`
` .set("spark.driver.extraClassPath","C:/mssql/spark-mssql-connector_2.12-1.2.0.jar") `

this is the code

```
#%%
# CONFIGURE THE SECTION
conf = SparkConf() \
    .setAppName(appName) \
    .setMaster(master) \
    .set("spark.driver.extraClassPath","C:/mssql/mssql-jdbc-8.4.1.jre8.jar") \
    .set("spark.driver.extraClassPath","C:/mssql/spark-mssql-connector_2.12-1.2.0.jar") \
    .set("spark.sql.execution.arrow.enabled", True) \
    .set("spark.sql.legacy.timeParserPolicy", "LEGACY")

sc = SparkContext.getOrCreate(conf=conf)
sqlContext = SQLContext(sc)
spark = sqlContext.sparkSession

# %%
# SQL SERVER VARIABLES
hostname = "hostname"
database = "database"
port = "port"
table = "table"
user = "user"
password  = "password"

# %%
# LOAD THE DATA FROM THE SQL SERVER
MSSQL_DW3_DIM_ITM = spark.read \
    .format("com.microsoft.sqlserver.jdbc.spark") \
    .option("url", f"jdbc:sqlserver://{hostname}:{port};databaseName={database}") \
    .option("dbtable", table) \
    .option("user", user) \
    .option("password", password) \
    .load()
```

I have this error:

```
Py4JJavaError: An error occurred while calling o64.load.
: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$2(JDBCOptions.scala:108)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:108)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:38)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:32)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:355)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:325)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:307)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:307)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
```
Could you tell me how did you solve it?

Thanks.

**Comment by cmcdougall** [comment]
I also ran into the same issue, a more explicit mention that this dependency should be included alongside the SQL Spark Connector, may make using the connector a lot easier for those unfamiliar.

**Comment by luxu1-ms** [comment]
Close inactive issue
