### ISSUE TITLE
Missleading error when inserting wrong data type

### ISSUE THREAD

**Issue by chalabaj** [microsoft/sql-spark-connector#183]
Hi,

When we try to write timestamp-like string 
`select  date_format(TO_DATE("2022.04.25", 'dd.MM.yyyy'), "yyyy-MM-dd HH:mm:ss")`
from Azure Databricks into A-SQL, the **spark results in error**: 

`Job aborted due to stage failure.
Caused by: SQLServerException: **The connection is closed**.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:1217)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:3508)
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.savePartition(BulkCopyUtils.scala:68)
	at com.microsoft.sqlserver.jdbc.spark.SingleInstanceWriteStrategies$.$anonfun$write$2(BestEffortSingleInstanceStrategy.scala:43)
	at com.microsoft.sqlserver.jdbc.spark.SingleInstanceWriteStrategies$.$anonfun$write$2$adapted(BestEffo`

which is highly missleading error message. Typically, the errorneous data type inserts return:
```
Job aborted due to stage failure.
Caused by: SQLServerException: An error occurred while converting the String value to JDBC data type INTEGER.
Caused by: ClassCastException: java.lang.String cannot be cast to java.lang.Integer
```
Configurations:
**Databricks**:
- Spark single node cluster: 9.1 LTS (includes Apache Spark 3.1.2, Scala 2.12)
- Library installed: com.microsoft.azure:spark-mssql-connector_2.12:1.2.0

**A-SQL**: 
 -  Microsoft SQL Azure (RTM) - 12.0.2000.8  Feb 23 2022 11:32:53
 
Spark Write code:
```
          pDfElt.distinct().write
                .format("com.microsoft.sqlserver.jdbc.spark")
                .option("url", pSqlConnectionString)
                .option("driver", vSqlDriver) 
                .mode("append") 
                .option("dbtable", pTableName)
                .option("tableLock", true)
                .option("schemaCheckEnabled", false)
                .option("CheckConstraints", false)
                .save() 
```

**Comment by luxu1-ms** [comment]
@chalabaj [date_format](https://docs.microsoft.com/en-us/azure/databricks/sql/language-manual/functions/date_format) converts a timestamp to a string. It looks like the column in Azure SQL is datetime type thus you have this error.

**Comment by luxu1-ms** [comment]
Close the issue for now. Please reopen if you have more questions.
