### ISSUE TITLE
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '_0'.

### ISSUE THREAD

**Issue by 2MD** [microsoft/sql-spark-connector#194]
In version lib:  
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>spark-mssql-connector_${scala.compat.version}</artifactId>
            <version>1.2.0</version>
        </dependency>

scala = 2.12       
When i use reliabilityLevel = 'NO_DUPLICATES' and SaveMode.Overwrite i catch:

22/07/18 07:43:00 ERROR BulkCopyUtils: execute update failed with error Incorrect syntax near '_0'.
22/07/18 07:43:00 ERROR ReliableSingleInstanceStrategy: createStagingTables: Exception while creating table [##application_1654697395085_115126_[stg].[1c_goods_in_stock_reg_raw]_0] : Incorrect syntax near '_0'.
22/07/18 07:43:00 ERROR ApplicationMaster: User class threw exception: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '_0'.
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '_0'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3272)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeUpdate(SQLServerStatement.java:710)
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.executeUpdate(BulkCopyUtils.scala:465)
	at com.microsoft.sqlserver.jdbc.spark.ReliableSingleInstanceStrategy$.createStagingTable(ReliableSingleInstanceStrategy.scala:240)
	at com.microsoft.sqlserver.jdbc.spark.ReliableSingleInstanceStrategy$.$anonfun$createStagingTables$2(ReliableSingleInstanceStrategy.scala:254)
	at com.microsoft.sqlserver.jdbc.spark.ReliableSingleInstanceStrategy$.$anonfun$createStagingTables$2$adapted(ReliableSingleInstanceStrategy.scala:253)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.microsoft.sqlserver.jdbc.spark.ReliableSingleInstanceStrategy$.createStagingTables(ReliableSingleInstanceStrategy.scala:253)
	at com.microsoft.sqlserver.jdbc.spark.ReliableSingleInstanceStrategy$.write(ReliableSingleInstanceStrategy.scala:55)
	at com.microsoft.sqlserver.jdbc.spark.SingleInstanceConnector$.writeInParallel(SingleInstanceConnector.scala:38)
	at com.microsoft.sqlserver.jdbc.spark.Connector.write(Connector.scala:68)      
	
**I can't find this row:
// remove square brackets in db / schema / table name
val dbtableNew = dbtable.replaceAll(“[\[\]]”, “”)

in ReliableSingleInstanceStrategy.scala**
[](url)

	 
<img width="1345" alt="Снимок экрана 2022-07-18 в 11 23 05" src="https://user-images.githubusercontent.com/14299153/179472759-f8355aff-8168-492d-beac-08877b6c0e83.png">

**Comment by moredatapls** [comment]
Does it work for you if instead of writing `.option("dbtable", "[stg].[1c_goods_in_stock_reg_raw]")` you write `.option("dbtable", "stg.1c_goods_in_stock_reg_raw")`?

**Comment by 2MD** [comment]
Then i'll have
User class threw exception: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near ****

**Comment by moredatapls** [comment]
> I saw, you fix this problem in master branch. But i can't find it in maven

@2MD: Since this repository here is not very active but the code contains some bugs we would like to see fixed, we at Solytic created a fork and just released v1.2.1 over there: https://github.com/solytic/sql-spark-connector/releases/tag/v1.2.1 It includes the bugfixes you mentioned.

Feel free to try this out and let me know whether it works for you. If something doesn't work out you can create an issue over at [our repo](https://github.com/solytic/sql-spark-connector), if you like

**Comment by 2MD** [comment]
I can't find it in maven
Could not find artifact com.microsoft.azure:spark-mssql-connector_2.12:pom:1.2.1 in central (https://repo1.maven.org/maven2/)

**Comment by moredatapls** [comment]
@2MD correct, since Microsoft did not release those bugfixes yet we created a fork and published the fix there. Head over to https://github.com/solytic/sql-spark-connector/releases/tag/v1.2.1 for instructions on how to import the dependency

**Comment by luxu1-ms** [comment]
Please see the latest version and this issue was fixed. https://search.maven.org/artifact/com.microsoft.azure/spark-mssql-connector/1.0.2/jar for spark 2.4. https://search.maven.org/search?q=a:spark-mssql-connector_2.12 for spark 3

**Comment by moredatapls** [comment]
@luxu1-ms I don't think this patch has been released

- #145 was merged on 8 Nov 2021
- but the latest published release is from 30 Aug 2021, so before the PR was merged - it can be seen [on the page you linked to](https://search.maven.org/artifact/com.microsoft.azure/spark-mssql-connector_2.12/1.2.0/jar)

**Comment by moredatapls** [comment]
@luxu1-ms could you check my previous message please?
