### ISSUE TITLE
NO_DUPLICATES” fails with com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '-'.

### ISSUE THREAD

**Issue by denzilribeiro** [microsoft/sql-spark-connector#22]
When you create with NO_DUPLICATES staging tables are created and dropped
Given App Names may have special characters, need to use QUOTENAME  when generating create/drop table syntax else there is a possibility of failure if the app name has some special character. This for example always fails on databricks

This is true for both the drop AND the create of staging tables.
https://docs.microsoft.com/en-us/sql/t-sql/functions/quotename-transact-sql?view=sql-server-ver15

TSQL Example:
drop table ##app-20200723122746-0000_627
 Msg 102, Level 15, State 1, Line 20
Incorrect syntax near '-'.

Log4j logs:
 /07/23 14:34:59 ERROR ReliableSingleInstanceStrategy: cleanupStagingTables: Exception while dropping table ##app-20200723122746-0000_407 :Incorrect syntax near '-'.
20/07/23 14:34:59 ERROR ReliableSingleInstanceStrategy: cleanupStagingTables: Exception while dropping table ##app-20200723122746-0000_408 :Incorrect syntax near '-'.
 
 
20/07/23 14:34:59 ERROR ScalaDriverLocal: User Code Stack Trace: 
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '-'.
                at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258)
                at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1535)
                at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:845)
                at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:752)
                at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
                at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
                at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)
                at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199)
                at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeUpdate(SQLServerStatement.java:680)
                at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.executeUpdate(BulkCopyUtils.scala:371)
                at com.microsoft.sqlserver.jdbc.spark.ReliableSingleInstanceStrategy$.com$microsoft$sqlserver$jdbc$spark$ReliableSingleInstanceStrategy$$createStagingTable(ReliableSingleInstanceStrategy.scala:223)
                at com.microsoft.sqlserver.jdbc.spark.ReliableSingleInstanceStrategy$$anonfun$createStagingTables$2.apply(ReliableSingleInstanceStrategy.scala:237)
                at com.microsoft.sqlserver.jdbc.spark.ReliableSingleInstanceStrategy$$anonfun$createStagingTables$2.apply(ReliableSingleInstanceStrategy.scala:236)
                at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
                at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
                at scala.collection.Iterator$class.foreach(Iterator.scala:891)

**Comment by ankitbko** [comment]
Spark App ID remains same for a spark context. In databricks multiple notebooks can run on same cluster which means all of them will have same spark app ID. This means multiple notebooks running at same time can cause conflicts in this case.

**Comment by ankitbko** [comment]
#49 Will also effect what name is choosen for global temp tables.

**Comment by bunkersdev** [comment]
Any updates on this ? We are seeing duplicates records show up in target tables.

**Comment by ChingChuan-Chen** [comment]
Any updates on this? I encountered this error, too.

**Comment by shivsood** [comment]
Closed.
