### ISSUE TITLE
SQL Synapse Support?

### ISSUE THREAD

**Issue by aravish** [microsoft/sql-spark-connector#66]
Could you please confirm if Azure SQL Synapse is officially supported? The doc mentions below

Note: Azure Synapse (Azure SQL DW) use is not tested with this connector. While it may work, there may be unintended consequences.

I get below error when writing to SQL Synapse
Caused by: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.ISQLServerBulkData
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at com.databricks.backend.daemon.driver.ClassLoaders$LibraryClassLoader.loadClass(ClassLoaders.scala:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 33 more

**Comment by swanderz** [comment]
plus one for Synapse SQL support!

**Comment by shivsood** [comment]
Connector is now available as part of Synapse. Closing.
