### ISSUE TITLE
[Spark 3.0.1] NoClassDefFoundError: org/apache/spark/internal/Logging$class

### ISSUE THREAD

**Issue by archanabwk** [microsoft/sql-spark-connector#87]
Here are the versions I'm using:
Spark: 3.0.1
Scala: 2.12.10
OS: Ubuntu 18.04 TLS

I'm trying SQL Server connection from PySpark script and running it using command: spark-submit
I have build then MSSQL connector using this repo https://github.com/microsoft/sql-spark-connector and changed the required versions inside build.sbt. But now, I'm facing below issue:

```File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o33.load.
: java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
	at com.microsoft.sqlserver.jdbc.spark.DefaultSource.<init>(DefaultSource.scala:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:734)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:248)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 20 more
```

Here is my build.sbt file:
```name := "spark-mssql-connector"
organization := "com.microsoft.sqlserver.jdbc.spark"
version := "1.0.0"
scalaVersion := "2.12.10"
val sparkVersion = "3.0.1"
javacOptions ++= Seq("-source", "1.8", "-target", "1.8", "-Xlint")
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-sql" % sparkVersion % "provided",
  // Spark Testing Utilities
  "org.apache.spark" %% "spark-core" % sparkVersion % "test" classifier
      "tests",
  "org.apache.spark" %% "spark-sql" % sparkVersion% "test" classifier
      "tests",
  "org.apache.spark" %% "spark-catalyst" % sparkVersion % "test" classifier
      "tests",
  "org.scalatest" %% "scalatest" % "3.0.8" % "test",
  "com.novocode" % "junit-interface" % "0.11" % "test",
  //SQLServer JDBC jars
  "com.microsoft.sqlserver" % "mssql-jdbc" % "8.2.2.jre8"
)
scalacOptions := Seq("-unchecked", "-deprecation", "evicted")
// Exclude scala-library from this fat jar. The scala library is already there in spark package.
assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false)
```

Please help.

**Comment by archanabwk** [comment]
Any updates on this? The MSSQL connector created by following the build steps doesn't work with latest Scala and Spark versions. Anyone facing same issue?

**Comment by arvindshmicrosoft** [comment]
Please use the preview version of the connector (Maven coordinate `com.microsoft.azure:spark-mssql-connector_2.12_3.0:1.0.0-alpha`) to use with Spark 3.x

**Comment by archanabwk** [comment]
@arvindshmicrosoft I have already tried that, still getting same issue.

**Comment by prodekan** [comment]
> @arvindshmicrosoft I have already tried that, still getting same issue.

Same here. Getting:
`Py4JJavaError: An error occurred while calling o630.load.
: java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
	at com.microsoft.sqlserver.jdbc.spark.DefaultSource.<init>(DefaultSource.scala:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:807)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:358)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 20 more`

I use the `com.microsoft.azure:spark-mssql-connector_2.12_3.0:1.0.0-alpha` connector.
Spark: 3.1.1
Scala: 2.12

**Comment by arvindshmicrosoft** [comment]
@prodekan - could you please share the snippet of code, as well as the runtime environment (i.e. is this Azure Databricks, Synapse, or a manually-deployed cluster)?

**Comment by prodekan** [comment]
> @prodekan - could you please share the snippet of code, as well as the runtime environment (i.e. is this Azure Databricks, Synapse, or a manually-deployed cluster)?

`df.write \
        .format("com.microsoft.sqlserver.jdbc.spark") \
        .mode("overwrite") \
        .option("url", url) \
        .option("dbtable", tablename) \
        .option("truncate", "true") \
        .option("accessToken", access_token) \
        .option("encrypt", "true") \
        .option("databaseName", database) \
        .option("hostNameInCertificate", host_name_in_certificate) \
        .option("tabLock", "true") \
        .option("reliabilityLevel", "BEST_EFFORT") \
        .option("schemaCheckEnabled", "false") \
        .option("bulkCopyBatchSize", "100000") \
        .save()`

Runtime Env: `Azure Databricks`.
Databricks runtime version: `8.1 (includes Apache Spark 3.1.1, Scala 2.12)`

**Comment by arvindshmicrosoft** [comment]
Unfortunately, it looks like you are hitting the same fundamental set of issues as described in #97. A community contribution is here: #100 - you might be able to adapt that till there is a formal update from the team here regarding Spark 3.1.1 support.

BTW, switching to DBR 7.x would be another option if you are willing to work with Spark 3.0.1.

cc: @shivsood @luxu1-ms @DaniBunny

**Comment by prodekan** [comment]
> Unfortunately, it looks like you are hitting the same fundamental set of issues as described in #97. A community contribution is here: #100 - you might be able to adapt that till there is a formal update from the team here regarding Spark 3.1.1 support.
> 
> BTW, switching to DBR 7.x would be another option if you are willing to work with Spark 3.0.1.
> 
> cc: @shivsood @luxu1-ms @DaniBunny

Thank you. I will try it.

**Comment by NathanNZ** [comment]
Is there a timeline for when the team will support 3.1? It's been out for a few months now. Code bases that depend on the Delta Lake improvements in Azure Databricks 8.x would be much easier to maintain without forking off the main code, merging in the fix and redeploying internally!

**Comment by shivsood** [comment]
@luxu1-ms @DaniBunny as FYI on Spark 3.1 support request. Also looks like spark 3.0.1 has the same issue. Have we tested on spark 3.0.1 ?
