### ISSUE TITLE
spark-mssql-connector_2.12_3.0-1.0.0-alpha on spark 3.0.2 with java.lang.SecurityException

### ISSUE THREAD

**Issue by DBNLP** [microsoft/sql-spark-connector#89]
Spark 3.0.2 using spark-mssql-connector_2.12_3.0-1.0.0-alpha write to sql server shows missing ISQLServerBulkData
adding mssql-jdbc-9.2.0.jre8.jar to the project library, now it shows: Exception in thread "main" java.lang.SecurityException: class "com.microsoft.sqlserver.jdbc.ISQLServerBulkData"'s signer information does not match signer information of other classes in the same package

I also tried: mssql-jdbc-8.2.2.jre8, but it has the same result java.lang.SecurityException

If the spark-mssql-connector_2.12_3.0-1.0.0-alpha compatible with Spark 3.0.2?

**Comment by shivsood** [comment]
Looks like issue of multiple JDBC jars in your class path. Please reopen with logs if still an issue.

**Comment by DBNLP** [comment]
Hi There, i now try with spark 3.1.2 and it has different error message:

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.schemaString(Lorg/apache/spark/sql/Dataset;Ljava/lang/String;Lscala/Option;)Ljava/lang/String;
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.mssqlCreateTable(BulkCopyUtils.scala:506)
	at com.microsoft.sqlserver.jdbc.spark.SingleInstanceConnector$.createTable(SingleInstanceConnector.scala:46)
	at com.microsoft.sqlserver.jdbc.spark.Connector.write(Connector.scala:90)
	at com.microsoft.sqlserver.jdbc.spark.DefaultSource.createRelation(DefaultSource.scala:64)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
	at NoteExtract$.main(NoteExtract.scala:391)
	at NoteExtract.main(NoteExtract.scala)

the code i am using is:
finalNote.write
        .format("com.microsoft.sqlserver.jdbc.spark")
        .mode("overwrite") //append another option
        .option("truncate",true)
        .option("url", targetURL)
        .option("dbtable", "MRTX99")
        .option("user", targetUser)
        .option("password", targetPswd)
        .save()

targetURL format is = "jdbc:sqlserver://{SERVER_ADDR}:1433;" + "databaseName=" + database_name 

it complaints no method found, however if i switch into spark driver all is successful.

I make sure only one jdbc driver attach to intellij spark project library, in this case is:  spark-mssql-connector_2.12_3.0-1.0.0-alpha.jar

Any idea?
